# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIWIP.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys
import serial

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 800, 550))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.userPanel = QtWidgets.QWidget()
        self.userPanel.setObjectName("userPanel")
        self.RFOutput = QtWidgets.QGroupBox(self.userPanel)
        self.RFOutput.setGeometry(QtCore.QRect(10, 10, 231, 51))
        self.RFOutput.setObjectName("RFOutput")
        self.RFOutOn = QtWidgets.QPushButton(self.RFOutput)
        self.RFOutOn.setGeometry(QtCore.QRect(20, 20, 81, 21))
        self.RFOutOn.setCheckable(True)
        self.RFOutOn.setObjectName("RFOutOn")
        self.RFOutOn.setStyleSheet("QPushButton"
                             "{"
                             "background-color : lightgrey;"
                             "}"
                             "QPushButton::pressed"
                             "{"
                             "background-color : grey;"
                             "}"
                             ) 
        self.RFOutOff = QtWidgets.QPushButton(self.RFOutput)
        self.RFOutOff.setGeometry(QtCore.QRect(130, 20, 81, 21))
        self.RFOutOff.setCheckable(True)
        self.RFOutOff.setChecked(True)
        self.RFOutOff.setDefault(False)
        self.RFOutOff.setFlat(False)
        self.RFOutOff.setObjectName("RFOutOff")
        self.RFOutOff.setStyleSheet("QPushButton"
                             "{"
                             "background-color : lightgrey;"
                             "}"
                             "QPushButton::pressed"
                             "{"
                             "background-color : grey;"
                             "}"
                             ) 
        self.operation = QtWidgets.QGroupBox(self.userPanel)
        self.operation.setGeometry(QtCore.QRect(20, 70, 361, 441))
        self.operation.setObjectName("operation")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.operation)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 20, 341, 391))
        self.tabWidget_2.setAcceptDrops(False)
        self.tabWidget_2.setAutoFillBackground(False)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_2.setUsesScrollButtons(True)
        self.tabWidget_2.setDocumentMode(True)
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setMovable(False)
        self.tabWidget_2.setTabBarAutoHide(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.CW = QtWidgets.QWidget()
        self.CW.setObjectName("CW")
        self.line1 = QtWidgets.QFrame(self.CW)
        self.line1.setGeometry(QtCore.QRect(0, 180, 341, 16))
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.label_3 = QtWidgets.QLabel(self.CW)
        self.label_3.setGeometry(QtCore.QRect(10, 200, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.CW)
        self.label_4.setGeometry(QtCore.QRect(10, 230, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.CW)
        self.label_5.setGeometry(QtCore.QRect(10, 260, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.LECW2 = QtWidgets.QLineEdit(self.CW)
        self.LECW2.setGeometry(QtCore.QRect(260, 200, 51, 20))
        self.LECW2.setObjectName("LECW2")
        self.label_40 = QtWidgets.QLabel(self.CW)
        self.label_40.setGeometry(QtCore.QRect(10, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(8)
        font.setKerning(True)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.CW)
        self.label_41.setGeometry(QtCore.QRect(10, 40, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.LECW1 = QtWidgets.QLineEdit(self.CW)
        self.LECW1.setGeometry(QtCore.QRect(260, 10, 51, 20))
        self.LECW1.setObjectName("LECW1")
        self.tabWidget_2.addTab(self.CW, "")
        self.pulsing = QtWidgets.QWidget()
        self.pulsing.setObjectName("pulsing")
        self.label_13 = QtWidgets.QLabel(self.pulsing)
        self.label_13.setGeometry(QtCore.QRect(10, 230, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.LEPusling4 = QtWidgets.QLineEdit(self.pulsing)
        self.LEPusling4.setGeometry(QtCore.QRect(260, 200, 51, 20))
        self.LEPusling4.setObjectName("LEPusling4")
        self.line1_2 = QtWidgets.QFrame(self.pulsing)
        self.line1_2.setGeometry(QtCore.QRect(0, 180, 341, 16))
        self.line1_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1_2.setObjectName("line1_2")
        self.label_14 = QtWidgets.QLabel(self.pulsing)
        self.label_14.setGeometry(QtCore.QRect(10, 200, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.pulsing)
        self.label_15.setGeometry(QtCore.QRect(10, 260, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_24 = QtWidgets.QLabel(self.pulsing)
        self.label_24.setGeometry(QtCore.QRect(10, 40, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.pulsing)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(8)
        font.setKerning(True)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.LEPulsing3 = QtWidgets.QLineEdit(self.pulsing)
        self.LEPulsing3.setGeometry(QtCore.QRect(260, 70, 51, 20))
        self.LEPulsing3.setObjectName("LEPulsing3")
        self.label_42 = QtWidgets.QLabel(self.pulsing)
        self.label_42.setGeometry(QtCore.QRect(10, 70, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.LEPulsing1 = QtWidgets.QLineEdit(self.pulsing)
        self.LEPulsing1.setGeometry(QtCore.QRect(260, 10, 51, 20))
        self.LEPulsing1.setObjectName("LEPulsing1")
        self.LEPulsing2 = QtWidgets.QLineEdit(self.pulsing)
        self.LEPulsing2.setGeometry(QtCore.QRect(260, 40, 51, 20))
        self.LEPulsing2.setObjectName("LEPulsing2")
        self.label_43 = QtWidgets.QLabel(self.pulsing)
        self.label_43.setGeometry(QtCore.QRect(10, 100, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.tabWidget_2.addTab(self.pulsing, "")
        self.dualLevel = QtWidgets.QWidget()
        self.dualLevel.setObjectName("dualLevel")
        self.LEDL2 = QtWidgets.QLineEdit(self.dualLevel)
        self.LEDL2.setGeometry(QtCore.QRect(260, 40, 51, 20))
        self.LEDL2.setObjectName("LEDL2")
        self.label_44 = QtWidgets.QLabel(self.dualLevel)
        self.label_44.setGeometry(QtCore.QRect(10, 100, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_26 = QtWidgets.QLabel(self.dualLevel)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(8)
        font.setKerning(True)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.LEDL1 = QtWidgets.QLineEdit(self.dualLevel)
        self.LEDL1.setGeometry(QtCore.QRect(260, 10, 51, 20))
        self.LEDL1.setObjectName("LEDL1")
        self.label_27 = QtWidgets.QLabel(self.dualLevel)
        self.label_27.setGeometry(QtCore.QRect(10, 40, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_45 = QtWidgets.QLabel(self.dualLevel)
        self.label_45.setGeometry(QtCore.QRect(10, 70, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.LEDL3 = QtWidgets.QLineEdit(self.dualLevel)
        self.LEDL3.setGeometry(QtCore.QRect(260, 70, 51, 20))
        self.LEDL3.setObjectName("LEDL3")
        self.label_46 = QtWidgets.QLabel(self.dualLevel)
        self.label_46.setGeometry(QtCore.QRect(10, 130, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.dualLevel)
        self.label_47.setGeometry(QtCore.QRect(10, 160, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.line1_7 = QtWidgets.QFrame(self.dualLevel)
        self.line1_7.setGeometry(QtCore.QRect(0, 180, 341, 16))
        self.line1_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1_7.setObjectName("line1_7")
        self.LEDL4 = QtWidgets.QLineEdit(self.dualLevel)
        self.LEDL4.setGeometry(QtCore.QRect(260, 100, 51, 20))
        self.LEDL4.setObjectName("LEDL4")
        self.LEDL5 = QtWidgets.QLineEdit(self.dualLevel)
        self.LEDL5.setGeometry(QtCore.QRect(260, 200, 51, 20))
        self.LEDL5.setObjectName("LEDL5")
        self.label_48 = QtWidgets.QLabel(self.dualLevel)
        self.label_48.setGeometry(QtCore.QRect(10, 290, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.dualLevel)
        self.label_49.setGeometry(QtCore.QRect(10, 200, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(8)
        font.setKerning(True)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.dualLevel)
        self.label_50.setGeometry(QtCore.QRect(10, 350, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.dualLevel)
        self.label_51.setGeometry(QtCore.QRect(10, 320, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.dualLevel)
        self.label_52.setGeometry(QtCore.QRect(10, 230, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.dualLevel)
        self.label_53.setGeometry(QtCore.QRect(10, 260, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.LEDL6 = QtWidgets.QLineEdit(self.dualLevel)
        self.LEDL6.setGeometry(QtCore.QRect(260, 230, 51, 20))
        self.LEDL6.setObjectName("LEDL6")
        self.tabWidget_2.addTab(self.dualLevel, "")
        self.AnalogInput = QtWidgets.QWidget()
        self.AnalogInput.setObjectName("AnalogInput")
        self.tabWidget_2.addTab(self.AnalogInput, "")
        self.CWSend = QtWidgets.QPushButton(self.operation)
        self.CWSend.setGeometry(QtCore.QRect(260, 410, 75, 23))
        self.CWSend.setObjectName("CWSend")
        self.CWRead = QtWidgets.QPushButton(self.operation)
        self.CWRead.setGeometry(QtCore.QRect(170, 410, 75, 23))
        self.CWRead.setObjectName("CWRead")
        self.outputOnDuration = QtWidgets.QGroupBox(self.userPanel)
        self.outputOnDuration.setGeometry(QtCore.QRect(450, 70, 271, 101))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(8)
        self.outputOnDuration.setFont(font)
        self.outputOnDuration.setObjectName("outputOnDuration")
        self.OODRead = QtWidgets.QPushButton(self.outputOnDuration)
        self.OODRead.setGeometry(QtCore.QRect(90, 70, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(8)
        self.OODRead.setFont(font)
        self.OODRead.setObjectName("OODRead")
        self.OODSend = QtWidgets.QPushButton(self.outputOnDuration)
        self.OODSend.setGeometry(QtCore.QRect(180, 70, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(8)
        self.OODSend.setFont(font)
        self.OODSend.setObjectName("OODSend")
        self.lineEdit = QtWidgets.QLineEdit(self.outputOnDuration)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 31, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.outputOnDuration)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 30, 41, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(self.outputOnDuration)
        self.label_6.setGeometry(QtCore.QRect(60, 30, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.outputOnDuration)
        self.label_7.setGeometry(QtCore.QRect(170, 30, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.readAll = QtWidgets.QPushButton(self.userPanel)
        self.readAll.setGeometry(QtCore.QRect(610, 190, 101, 21))
        self.readAll.setDefault(False)
        self.readAll.setObjectName("readAll")
        self.restoreDefaults = QtWidgets.QPushButton(self.userPanel)
        self.restoreDefaults.setGeometry(QtCore.QRect(610, 220, 101, 21))
        self.restoreDefaults.setDefault(False)
        self.restoreDefaults.setObjectName("restoreDefaults")
        self.otherReadback = QtWidgets.QGroupBox(self.userPanel)
        self.otherReadback.setGeometry(QtCore.QRect(470, 280, 251, 231))
        self.otherReadback.setObjectName("otherReadback")
        self.label_8 = QtWidgets.QLabel(self.otherReadback)
        self.label_8.setGeometry(QtCore.QRect(20, 30, 161, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.otherReadback)
        self.label_9.setGeometry(QtCore.QRect(20, 60, 161, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.otherReadback)
        self.label_10.setGeometry(QtCore.QRect(20, 90, 161, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.otherReadback)
        self.label_11.setGeometry(QtCore.QRect(20, 120, 161, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.otherReadback)
        self.label_12.setGeometry(QtCore.QRect(20, 170, 161, 16))
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.userPanel, "")
        self.internalValues = QtWidgets.QWidget()
        self.internalValues.setObjectName("internalValues")
        self.tabWidget.addTab(self.internalValues, "")
        self.waveform = QtWidgets.QWidget()
        self.waveform.setObjectName("waveform")
        self.tabWidget.addTab(self.waveform, "")
        self.eventLogs = QtWidgets.QWidget()
        self.eventLogs.setObjectName("eventLogs")
        self.tabWidget.addTab(self.eventLogs, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RFOutput.setTitle(_translate("MainWindow", "RF output"))
        self.RFOutOn.setText(_translate("MainWindow", "ON"))
        self.RFOutOff.setText(_translate("MainWindow", "Off"))
        self.operation.setTitle(_translate("MainWindow", "Operation"))
        self.label_3.setText(_translate("MainWindow", "Starting freq (MHz)"))
        self.label_4.setText(_translate("MainWindow", "Frequency readback (MHz)"))
        self.label_5.setText(_translate("MainWindow", "V-I phase readback (degree)"))
        self.label_40.setText(_translate("MainWindow", "Power Setpoint (W)"))
        self.label_41.setText(_translate("MainWindow", "Peak power readback (W)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.CW), _translate("MainWindow", "CW"))
        self.label_13.setText(_translate("MainWindow", "Frequency readback (MHz)"))
        self.label_14.setText(_translate("MainWindow", "Starting freq (MHz)"))
        self.label_15.setText(_translate("MainWindow", "V-I phase readback (degree)"))
        self.label_24.setText(_translate("MainWindow", "Duty cycle (%)"))
        self.label_25.setText(_translate("MainWindow", "Peak power Setpoint (W)"))
        self.label_42.setText(_translate("MainWindow", "Pulsing Frequency (Hz)"))
        self.label_43.setText(_translate("MainWindow", "Peak power readback (W)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.pulsing), _translate("MainWindow", "Pulsing"))
        self.label_44.setText(_translate("MainWindow", "Pulsing frequency (Hz)"))
        self.label_26.setText(_translate("MainWindow", "High State Power Setpoint (W)"))
        self.label_27.setText(_translate("MainWindow", "Low State Power Setpoint (W)"))
        self.label_45.setText(_translate("MainWindow", "Duty cycle (%)"))
        self.label_46.setText(_translate("MainWindow", "High State pwr readback (W)"))
        self.label_47.setText(_translate("MainWindow", "Low State pwr readback (W)"))
        self.label_48.setText(_translate("MainWindow", "Low State Frequency (MHz)"))
        self.label_49.setText(_translate("MainWindow", "High State Starting freq (MHz)"))
        self.label_50.setText(_translate("MainWindow", "Low State V-I phase (degree)"))
        self.label_51.setText(_translate("MainWindow", "High State V-I phase (degree)"))
        self.label_52.setText(_translate("MainWindow", "Low State Starting freq (MHz)"))
        self.label_53.setText(_translate("MainWindow", "High State Frequency (MHz)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.dualLevel), _translate("MainWindow", "Dual-Level"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.AnalogInput), _translate("MainWindow", "Analog Input"))
        self.CWSend.setText(_translate("MainWindow", "Send"))
        self.CWRead.setText(_translate("MainWindow", "Read"))
        self.outputOnDuration.setTitle(_translate("MainWindow", "Output On Duration"))
        self.OODRead.setText(_translate("MainWindow", "Read"))
        self.OODSend.setText(_translate("MainWindow", "Send"))
        self.lineEdit.setText(_translate("MainWindow", "0"))
        self.lineEdit_2.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "min"))
        self.label_7.setText(_translate("MainWindow", "sec"))
        self.readAll.setText(_translate("MainWindow", "Read All"))
        self.restoreDefaults.setText(_translate("MainWindow", "Restore Defaults"))
        self.otherReadback.setTitle(_translate("MainWindow", "Other readback"))
        self.label_8.setText(_translate("MainWindow", "DC current readback (A)"))
        self.label_9.setText(_translate("MainWindow", "DC voltage readback (V)"))
        self.label_10.setText(_translate("MainWindow", "RF current readback (Arms)"))
        self.label_11.setText(_translate("MainWindow", "RF voltage readback (Vms)"))
        self.label_12.setText(_translate("MainWindow", "Temperature Sensors (C)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.userPanel), _translate("MainWindow", "User Panel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.internalValues), _translate("MainWindow", "Internal Values"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.waveform), _translate("MainWindow", "Waveform"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.eventLogs), _translate("MainWindow", "Event Logs"))

    def toggle(self, MainWindow, _bool, button1, button2):
        if(_bool):
            print("hi")
            button1.setChecked(False)
            button2.setChecked(True)
        elif(not _bool):
            print("hi2")
            button2.setChecked(False)
            button1.setChecked(True)
        self.reads[0].setChecked(True)

    def toggle2(self, MainWindow, _bool, z):
        if(_bool):
            print("hi")
            self.reads[z].setChecked(True)
            self.sends[z].setChecked(False)
        elif(not _bool):
            print("hi2")
            self.sends[z].setChecked(True)
            self.reads[z].setChecked(False)

    def tab2(self, MainWindow):
        names = [ "not used", "not used", "RF on",
            "operation mode",
            "high state power setpoint", 
            "low state power setpoint",
            "off period (duty cycle)",
            "total period (pulsing frequency)",
            "power controller P-Gain",
            "power controller I-Gain",
            "power controller D-gain",   
            "ui_rf_q_enable",
            "rf_q_polarity",
            "measured high state power",
            "measured low state power",       
            "phase controller P-Gain",
            "phase controller I-Gain",
            "temp sensor 1 and 2", 
            "temp sensor 3 and 4",
            "clear overtemp alarm",         
            "not used", 
            "operating frequency limits High-Pwr",
            "lock detected",
            "starting freq - high power state",
            "not used",
            "measured high state frequency",
            "measured low state frequency",
            "target operating phase (V To I)",
            "measured high state phase",
            "measured low state phase",
            "dc_hard_current_limit",  
            "not used", 
            "DC current limit",
            "DC current readback",
            "RF current limit",       
            "RF current readback",
            "not used", 
            "RF on duration",
            "Stream control",
            "Stream data",
            "adc_lvds_swing",      
            "adc_clk_delay",
            "adc_set_testmode",
            "adc_checkboard_test_error",
            "adc_offset_timeconstant"
        ]
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(8)

        labels = [QtWidgets.QLabel(self.internalValues) for i in range(45)]
       
        self.reads = [QtWidgets.QPushButton(self.internalValues) for i in range(45)]
        self.sends = [QtWidgets.QPushButton(self.internalValues) for i in range(45)]
        self.toggles = [[False, False] for i in range(45)]

        for x in range(45):
            labels[x].setAlignment(QtCore.Qt.AlignRight)
            labels[x].setFont(font)
            labels[x].setObjectName("label2_" + str(x+1))
            labels[x].setText("reg"+str(x)+ ": " + names[x])
            self.reads[x].setCheckable(True)
            self.reads[x].setObjectName("Read_" + str(x))
            self.reads[x].setText("Read")
            self.reads[x].setStyleSheet("QPushButton"
                             "{"
                             "background-color : lightgrey;"
                             "}"
                             "QPushButton::pressed"
                             "{"
                             "background-color : grey;"
                             "}"
                             ) 
            self.sends[x].setCheckable(True)
            self.sends[x].setObjectName("Read_" + str(x))
            self.sends[x].setText("Send")
            self.sends[x].setStyleSheet("QPushButton"
                             "{"
                             "background-color : lightgrey;"
                             "}"
                             "QPushButton::pressed"
                             "{"
                             "background-color : grey;"
                             "}"
                             ) 
            if x < 15:
                labels[x].setGeometry(QtCore.QRect(25, 50+30*x, 200, 20))
                self.reads[x].setGeometry(QtCore.QRect(325, 50+30*x, 40, 20))
                self.sends[x].setGeometry(QtCore.QRect(375, 50+30*x, 40, 20))
            elif x < 30:
                labels[x].setGeometry(QtCore.QRect(450, 50+30*(x-15), 200, 20))
                self.reads[x].setGeometry(QtCore.QRect(750, 50+30*(x-15), 40, 20))
                self.sends[x].setGeometry(QtCore.QRect(800, 50+30*(x-15), 40, 20))
            else:
                labels[x].setGeometry(QtCore.QRect(875, 50+30*(x-30), 200, 20))
                self.reads[x].setGeometry(QtCore.QRect(1175, 50+30*(x-30), 40, 20))
                self.sends[x].setGeometry(QtCore.QRect(1225, 50+30*(x-30), 40, 20))
        i = 0
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 0))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 0))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 1))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 1))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 2))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 2))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 3))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 3))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 4))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 4))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 5))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 5))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 6))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 6))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 7))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 7))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 8))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 8))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 9))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 9))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 10))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 10))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 11))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 11))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 12))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 12))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 13))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 13))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 14))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 14))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 15))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 15))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 16))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 16))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 17))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 17))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 18))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 18))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 19))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 19))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 20))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 20))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 21))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 21))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 22))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 22))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 23))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 23))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 24))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 24))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 25))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 25))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 26))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 26))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 27))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 27))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 28))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 28))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 29))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 29))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 30))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 30))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 31))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 31))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 32))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 32))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 33))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 33))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 34))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 34))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 35))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 35))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 36))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 36))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 37))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 37))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 38))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 38))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 39))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 39))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 40))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 40))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 41))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 41))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 42))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 42))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 43))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 43))
        i = i+1
        self.reads[i].clicked.connect(lambda: self.toggle2(MainWindow, True, 44))
        self.sends[i].clicked.connect(lambda: self.toggle2(MainWindow, False, 44))

    def transition(self, MainWindow):
        if(self.tabWidget.currentIndex() == 1):
            MainWindow.resize(1300, 550)
            self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1300, 550))
            for i in range(45):
            	self.reads[i].setChecked(False)
            	self.sends[i].setChecked(False)
        else:
            self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 800, 550))
            MainWindow.resize(800, 550)

#My computer doesnt have a serial port, but this should work to open the serial port on the computer in the lab, if I get access it should be easier for me to figure it out
if __name__ == "__main__":
    ser = serial.Serial('/dev/ttyUSB0')
    print(ser.name)
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.tab2(MainWindow)

    ui.tabWidget.currentChanged.connect(lambda:ui.transition(MainWindow))
    

    ui.RFOutOn.clicked.connect(lambda:ui.toggle(MainWindow, True, ui.RFOutOff, ui.RFOutOn))
    ui.RFOutOff.clicked.connect(lambda:ui.toggle(MainWindow, False, ui.RFOutOff, ui.RFOutOn))
   
    



    MainWindow.show()
    sys.exit(app.exec_())
